name: workspace_core
description: A new Flutter project.
version: 21.2.11
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_core

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  vector_math: ^2.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
